export enum AuditAction {
  LOGIN = 'signed in',
  PASSWORD_RESET = 'reset the password of',
  ACCOUNT_CREATED = 'created an account for',
  ACCOUNT_DELETED = 'deleted the account of',
  ACCOUNT_RESTORED = 'restored the account of',
  ADMIN_CREATED = 'created an admin account for',
  SESSION_REVOKED = 'ended a session for',
  PATIENT_LINKED = 'linked',
  PATIENT_VERIFIED = 'verified',
  PATIENT_UNVERIFIED = 'removed verification for',
  STAFF_ASSIGNED = 'assigned a physiotherapist to',
  ASSIGNMENT_CREATED = 'assigned an exercise to',
  ASSIGNMENT_UPDATED = 'updated an assignment for',
  ASSIGNMENT_DELETED = 'removed an assignment for',
  SCHEDULE_CREATED = 'scheduled sessions for',
  SCHEDULE_CANCELLED = 'cancelled a scheduled session for',
  SESSION_COMPLETED = 'completed a session for',
  EXERCISE_CREATED = 'created the exercise',
  IMPERSONATION = 'impersonated',
  SCHEDULE_UPDATED = 'updated a scheduled session for',
}
