// landmark.constant.ts
export const LANDMARK_KEYS = [
  'leftShoulderPosition',
  'leftElbowPosition',
  'leftWristPosition',
  'rightShoulderPosition',
  'rightElbowPosition',
  'rightWristPosition',
  'leftHipPosition',
  'rightHipPosition',
  'leftKneePosition',
  'rightKneePosition',
  'leftAnklePosition',
  'rightAnklePosition',
  'nosePosition',
  'leftEyePosition',
  'rightEyePosition',
  'leftEarPosition',
  'rightEarPosition',
  'leftMouthPosition',
  'rightMouthPosition',
  'leftIndexPosition',
  'rightIndexPosition',
  'leftPinkyPosition',
  'rightPinkyPosition',
  'leftThumbPosition',
  'rightThumbPosition',
  'leftFootIndexPosition',
  'rightFootIndexPosition',
  'leftHeelPosition',
  'rightHeelPosition',
] as const;

export type LandmarkKey = (typeof LANDMARK_KEYS)[number];
